[[custom_groups]]
name = "â™»ï¸ è‡ªåŠ¨é€‰æ‹©"
type = "url-test"
rule = [".*(s3|s4|s5).*"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ’¬ ChatGPT"
type = "select"
rule = ["[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©", "[]ğŸ¯ å…¨çƒç›´è¿", "[]ğŸ›‘ å…¨çƒæ‹¦æˆª", ".*"]

[[custom_groups]]
name = "ï£¿ Apple Location"
type = "select"
rule = ["[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©", "[]ğŸ¯ å…¨çƒç›´è¿", "[]ğŸ›‘ å…¨çƒæ‹¦æˆª", ".*"]

[[custom_groups]]
name = "ğŸ’¬ Perplexity"
type = "select"
rule = ["[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©", "[]ğŸ¯ å…¨çƒç›´è¿", "[]ğŸ›‘ å…¨çƒæ‹¦æˆª", ".*"]

[[custom_groups]]
name = "â˜ï¸ Cloudflare"
type = "select"
rule = ["[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©", "[]ğŸ¯ å…¨çƒç›´è¿", "[]ğŸ›‘ å…¨çƒæ‹¦æˆª", ".*"]