[[rulesets]]
group = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
ruleset = "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
type = "clash-domain"
interval = 86400

[[rulesets]]
group = "ğŸ è‹¹æœæœåŠ¡"
ruleset = "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
type = "clash-domain"
interval = 86400

[[rulesets]]
group = "ğŸ è‹¹æœæœåŠ¡"
ruleset = "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
type = "clash-domain"
interval = 86400

[[rulesets]]
group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
type = "clash-domain"
interval = 86400

[[rulesets]]
group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
type = "clash-domain"
interval = 86400

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
type = "clash-domain"
interval = 86400

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
type = "clash-domain"
interval = 86400

[[rulesets]]
group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
type = "clash-domain"
interval = 86400

[[rulesets]]
group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
type = "clash-domain"
interval = 86400

[[rulesets]]
group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
type = "clash-ipcidr"
interval = 86400

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
type = "clash-ipcidr"
interval = 86400

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
type = "clash-ipcidr"
interval = 86400

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
type = "clash-classic"
interval = 86400
