[[rulesets]]
group = "ğŸ’¬ ChatGPT"
ruleset = "subconverter-config/custom/rules/ChatGPT.list"

[[rulesets]]
group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
ruleset = "subconverter-config/custom/rules/proxy.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "subconverter-config/custom/rules/direct.list"